objectives = [
    {"name": "don't use any brightbugs",        "level": "easy", "props": ["predrangleic", "restriction"]},
    {"name": "don't use any weapon with primary thrust type", "level": "hard"},
    {"name": "don't use any resins",            "level": "easy", "props": ["predrangleic", "restriction"]},
    {"name": "don't use any magic",             "level": "easy", "props": ["predrangleic", "restriction"]},
    {"name": "don't use a bow",                 "level": "easy", "props": ["predrangleic", "restriction"]},
    {"name": "don't use any homeward bones",    "level": "easy", "props": ["predrangleic", "restriction"]},
    {"name": "don't use the Silver Cat Ring"},
    {"name": "don't kill any NPCs"},
    {"name": "don't speak to Lenigrast"},
    {"name": "don't use any small lifegems"},
    {"name": "kill the Pursuer without ballista or quick kill", "level": "easy", "props": "predrangleic"},
    {"name": "kill the Flexile Sentry",         "level": "easy", "props": "predrangleic"},
    {"name": "kill the Gank Squad"},
    {"name": "kill Sinh the Slumbering Dragon"},
    {"name": "kill Elana, Squalid Queen"},
    {"name": "kill the Blue Smelter Demon"},
    {"name": "kill the Fume Knight"},
    {"name": "kill Sir Alonne"},
    {"name": "kill the Burnt Ivory King"},
    {"name": "kill Aava the King's Pet"},
    {"name": "kill Lud and Zallen"},
    {"name": "kill the Rotten",                 "level": "easy", "props": "predrangleic"},
    {"name": "kill the Old Iron King",          "level": "easy", "props": "predrangleic"},
    {"name": "kill the Duke's Dear Freja",      "level": "easy", "props": "predrangleic"},
    {"name": "kill the Lost Sinner",            "level": "easy", "props": "predrangleic"},
    {"name": "kill the Executioner's Chariot",  "level": "easy", "props": "predrangleic"},
    {"name": "kill the Belfry Gargoyles",       "level": "easy", "props": "predrangleic"},
    {"name": "kill the Royal Rat Vanguard",     "level": "easy", "props": "predrangleic"},
    {"name": "kill the Royal Rat Authority",    "level": "easy", "props": "predrangleic"},
    {"name": "kill the Old Dragonslayer",       "level": "easy", "props": "predrangleic"},
    {"name": "Kill Velstadt",                   "level": "easy"},
    {"name": "kill Vendrick",                   "level": "easy", "props": "predrangleic"},
    {"name": "kill Darklurker"},
    {"name": "kill Ancient Dragon"},
    {"name": "kill Aldia"},
    {"name": "kill Dragonrider with a full arena", "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Stone Ring",           "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Hawk Ring",            "level": "easy", "props": "predrangleic"},
    {"name": "obtain Cale's Helm",              "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Ring of Binding",      "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Knight Set",           "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Royal Soldier's Ring +0", "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Ring of Giants +0",    "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Bone Staff",           "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Archdrake Shield",     "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Hush sorcery",         "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Ring of Knowledge",    "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Forlorn Hood",         "level": "easy", "props": "predrangleic"},
    {"name": "obtain a Dragon Tooth",           "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Blue Tearstone Ring",  "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Blossom Kite Shield",  "level": "easy", "props": "predrangleic"},
    {"name": "obtain Flame Weapon",             "level": "easy", "props": "predrangleic"},
    {"name": "obtain Ricard's Rapier",          "level": "easy", "props": "predrangleic"},
    {"name": "obtain Soul Spear",               "level": "easy", "props": "predrangleic"},
    {"name": "obtain the spell Chameleon",      "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Old Knight Pike",      "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Poinsonbite Ring",     "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Mirrah Shield",        "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Covetous Gold Serpent Ring +0", "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Ash Knuckle Ring",     "level": "easy", "props": "predrangleic"},
    {"name": "obtain Havel's Armor Set",        "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Dark Pyromancy Flame", "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Heide Lance",          "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Bandit's Greataxe",    "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Shotel",               "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Great Magic Weapon sorcery", "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Old Sun Ring",         "level": "easy", "props": "predrangleic"},
    {"name": "kill Vengarl's body",             "level": "easy", "props": "predrangleic"},
    {"name": "kill Vengarl's head",             "level": "easy", "props": "predrangleic"},
    {"name": "obtain a Murakumo",               "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Santier's Spear",      "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Gyrm Axe",             "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Staff of Wisdom",      "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Pickaxe"},
    {"name": "obtain the Engraved Gauntlets",   "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Priestess Set",        "level": "easy", "props": "predrangleic"},
    {"name": "obtain Gower's Ring of Protection", "level": "easy"},
    {"name": "obtain the Singer's Dress",       "level": "easy"},
    {"name": "obtain the Red Iron Twinblade",   "level": "easy"},
    {"name": "obtain the Helix Halberd",        "level": "easy"},
    {"name": "obtain both pyromancy flames"},
    {"name": "obtain the King's Crown",         "level": "easy"},
    {"name": "obtain the Avelyn",               "level": "easy"},
    {"name": "obtain Oldenford's Staff",        "level": "easy"},
    {"name": "activate the dragon in Aldia's Keep"},
    {"name": "obtain a Dragon Acolyte Mask",    "level": "easy"},
    {"name": "obtain the Northern Ritual Band +2", "level": "easy"},
    {"name": "obtain 4 Rings of the Evil Eye"},
    {"name": "obtain the Third Dragon Ring",    "level": "easy"},
    {"name": "obtain the Drangleic Helm"},
    {"name": "obtain the Giant Warrior Club",   "level": "easy"},
    {"name": "obtain the Sanctum Mace",         "level": "easy", "props": "predrangleic"},
    {"name": "obtain Promised Walk of Peace",   "level": "easy", "props": "predrangleic"},
    {"name": "obtain Denial",                   "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Puzzling Stone Sword", "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Drakeblood Greatsword", "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Sanctum Shield"},
    {"name": "obtain the Simpleton's Ring"},
    {"name": "obtain the Pilgrim's Spontoon"},
    {"name": "obtain the Majestic Greatsword"},
    {"name": "obtain Outcry"},
    {"name": "obtain the Curved Nil Greatsword"},
    {"name": "obtain the Old Bell Helm"},
    {"name": "obtain the Ring of the Embedded"},
    {"name": "obtain the Ivory Warrior Ring"},
    {"name": "obtain the Bone Fist"},
    {"name": "obtain the Blacksmith's Hammer",  "level": "easy", "props": "predrangleic"},
    {"name": "obtain Unleash Magic",            "level": "easy"},
    {"name": "obtain the Ring of Resistance",   "level": "easy", "props": "predrangleic"},
    {"name": "join the Heirs of the Sun",       "level": "easy", "props": "predrangleic"},
    {"name": "join the Way of the Blue",        "level": "easy", "props": "predrangleic"},
    {"name": "join the Brotherhood of Blood",   "level": "easy", "props": "predrangleic"},
    {"name": "join the Blue Sentinels",         "level": "easy", "props": "predrangleic"},
    {"name": "join the Bell Keepers",           "level": "easy", "props": "predrangleic"},
    {"name": "join the Rat King covenant",      "level": "easy", "props": "predrangleic"},
    {"name": "join the Dragon Remnants covenant", "level": "easy"},
    {"name": "join the Company of Champions",   "level": "easy", "props": "predrangleic"},
    {"name": "join the Pilgrims of Dark",       "level": "easy"},
    {"name": "obtain Ring of Blades +0, +1, and +2"},
    {"name": "get all gestures"},
    {"name": "use Gillian to place any ladder", "level": "easy", "props": "predrangleic"},
    {"name": "obtain the Mirrah Greatsword",    "level": "easy", "props": "predrangleic"},
    {"name": "Parry 5 bosses"},
    {"name": "light all 5 bonfires in The Lost Bastile", "level": "easy", "props": "predrangleic"},
    {"name": "light all 5 bonfires in Brume Tower"},
    {"name": "light all 5 bonfires in Eleum Loyce"},
    {"name": "light all 4 bonfires in Forest of Fallen Giants", "level": "easy", "props": "predrangleic"},
    {"name": "light all 4 bonfires in Drangleic Castle", "level": "easy"},
    {"name": "light all 4 bonfires in Shrine of Amana", "level": "easy"},
    {"name": "infuse a weapon",                 "level": "easy", "props": "predrangleic"},
    {"name": "Kill Benhart of Jugo",            "level": "easy", "props": "predrangleic", "clash": "shrodinger benhart"},
    {"name": "get 7 estus flask uses",          "level": "easy", "props": "predrangleic"},
    {"name": "upgrade the estus flask to +4",   "level": "easy", "props": "predrangleic"},
    {"name": "spice a spell at Magerold",       "level": "easy", "props": "predrangleic"},
    {"name": "Attune one of each type of spell at the same time"},
    {"name": "level a stat to 99",              "level": "easy", "props": "predrangleic"},
    {"name": "upgrade a weapon to +10",         "level": "easy", "props": "predrangleic"},
    {"name": "upgrade a weapon with twinkling titanite to +5"},
    {"name": "upgrade a weapon with petrified dragon bones to +5"},
    {"name": "traverse 2 fog walls from behind"},
    {"name": "kill 3 invisible hollows",        "level": "easy", "props": "predrangleic"},
    {"name": "obtain the ladle",                "level": "easy", "props": "predrangleic"},
    {"name": "change the nature of your being", "level": "easy", "props": "predrangleic"},
    {"name": "obtain black knight ultra greatsword", "level": "easy", "props": "predrangleic"},
    {"name": "obtain moonlight greatsword"},
    {"name": "obtain curved dragon greatsword", "level": "easy"},
    {"name": "invade and kill licia"},
    {"name": "kill 5 pursuers"},
    {"name": "kill a boss with consumables"},
    {"name": "kill a boss with torch"},
    {"name": "kill a boss with fists"},
    {"name": "kill a boss with a bow",          "level": "easy", "props": "predrangleic"},
    {"name": "kill a boss with a greatbow"},
    {"name": "kill a boss with a crossbow"},
    {"name": "kill a boss with the ladle"},
    {"name": "kill a boss on ng+7",             "level": "easy", "props": "predrangleic"},
    {"name": "kill a boss with a broken weapon"},
    {"name": "kill a boss with only pyromancy"},
    {"name": "kill a boss with only hexes"},
    {"name": "kill a boss with only miracles"},
    {"name": "kill a boss with only sorceries"},
    {"name": "kill a boss with a broken weapon"},
    {"name": "kill a boss with a boss weapon"},
    {"name": "kill a boss with it's own boss weapon"},
    {"name": "repair a weapon at the whipping tree", "level": "easy", "props": "predrangleic"},
    {"name": "kill Mauldron the Assassin"},
    {"name": "get unpoisoned by the gutter bug", "level": "easy", "props": "predrangleic"},
    {"name": "kill a boss dressed as havel with the dragon tooth (no greatshield)"},
    {"name": "kill a boss using a fire longsword while wearing vengarls helm and the drangleic sheild"},
    {"name": "reverse hollowing at the amana shrine", "level": "easy"},
    {"name": "start as deprived",               "level": "easy", "props": "predrangleic", "clash": "starting_class"},
    {"name": "start as cleric",                 "level": "easy", "props": "predrangleic", "clash": "starting_class"},
    {"name": "start as sorcerer",               "level": "easy", "props": "predrangleic", "clash": "starting_class"},
    {"name": "start without a gift",            "level": "easy", "props": "predrangleic", "clash": "starting_gift"},
    {"name": "start deprived with no gift",     "level": "easy", "props": "predrangleic",
        "clash": ["starting_class", "starting_gift"]},
    {"name": "get clear bluestone ring +0, +1, and +2"},
    {"name": "get chloranthy ring +0, +1, and +2"},
    {"name": "get life ring +0, +1, +2, and +3"},
    {"name": "get clear bluestone ring +0, +1, and +2"},
    {"name": "Have all available NPCs alive in Majula together (gathering of exiles)"},
    {"name": "Kill chariot without pulling the lever"},
    {"name": "Kill Gutter Denizen (gutter sconses)"},
    {"name": "Kill Greatsword Foreigner phantom (Things Betwitx)"},
    {"name": "do 5 trades with Dyna and Tillo", "level": "easy", "props": "predrangleic"},
    {"name": "obtain warmth",                   "level": "easy"},
    {"name": "talk to Gavlan in all 3 locations", "level": "easy", "props": "predrangleic"},
    {"name": "cut off things from 3 different bosses"},
    {"name": "kill a boss using only a shield"},
    {"name": "obtain darkdrift"},
    {"name": "obtain the Gyrm Greataxe"},
    {"name": "obtain the Dragonslayer Greatbow"},
    {"name": "obtain Chaos Blade"},
    {"name": "obtain the Crypt Black Sword"},
    {"name": "obtain the Moonlight Greatsword"},
    {"name": "have at least one of each arrow type in your inventory",  "level": "easy"},
    {"name": "have at least one of each great arrow type in your inventory"},
    {"name": "have at least one of each bolt type in your inventory",   "level": "easy"},
    {"name": "Purchase The Smelter Demon set"},
    {"name": "obtain the penal handcuffs"},
    {"name": "enter the fume knight fight wearing velstadts helm"},
    {"name": "obtain Flying Feline Boots",      "level": "easy", "props": "predrangleic"},
    {"name": "purchase all 4 pieces of the Moonlight Butterfly set"},
    {"name": "obtain the Ring of the Living"},
    {"name": "obtain Benhart's armour",         "level": "easy", "clash": "shrodinger benhart"},
    {"name": "obtain a lord soul without leveling", "level": "easy", "props": "predrangleic"},
    {"name": "don't wear rings for boss fights"},
    {"name": "obtain 2 darkdrift katanas",      "level": "easy"},
    {"name": "trade one boss soul with each vendor", "level": "easy", "props": "predrangleic"},
    {"name": "kill a boss with a whip"},
    {"name": "obtain Dragonslayer Greatbow",    "level": "easy", "props": "predrangleic"},
    {"name": "obtain chaos blade",              "level": "easy", "props": "predrangleic"},
    {"name": "obtain Crypt Blacksword",         "level": "easy", "props": "predrangleic"},
    {"name": "obtain Chime of Screams"},
    {"name": "Purchase The Smelter Demon set",  "level": "easy", "props": "predrangleic"},
    {"name": "Purchase Lost Sinner set",        "level": "easy", "props": "predrangleic"},
    {"name": "Purchase Looking Glass Knight set", "level": "easy"},
    {"name": "obtain Ring of the Living",       "level": "easy"},
    {"name": "obtain the ring of the dead",     "level": "easy"},
    {"name": "obtain Spell Quartz ring 0, +1, +2, and +3"},
    {"name": "obtain Thunder Quartz ring 0, +1, +2, and +3"},
    {"name": "obtain Flame Quartz ring 0, +1, +2, and +3"},
    {"name": "Kill a lord with the dagger",     "level": "easy", "props": "predrangleic"},
    {"name": "Kill a lord with the uchigatana"},
    {"name": "obtain 4 silver covertous serpent rings"},
    {"name": "obtain 6 covetous serpent rings (gold and silver)"},
    {"name": "kill a boss with the butterfly set"},
    {"name": "obtain Immolation",               "level": "easy", "props": "predrangleic"},
    {"name": "ring the bells of both belfries", "level": "easy", "props": "predrangleic"},
    {"name": "join all covenants"}
]

debug = range(5)
print(debug)
# print(type(debug))
print(objectives[0:3])
# objectives[0]["name"]

for item in objectives:
    if "level" in item:
        print(item["name"])
        print(item.get("lowest_diff"))
